"""Behaviour tests for figure matching and table structure validation.

Run with:  python -m pytest tests            (or)  python tests/test_...py

The fixtures are generated by `tests/make_fixtures.py`; each isolates one
behaviour, so a failure here names the rule that broke.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import fitz  # noqa: E402

from pdfval.extractor import reset_table_cache  # noqa: E402
from pdfval.validators import validate_images, validate_tables  # noqa: E402
from pdfval.validators.content import validate_content  # noqa: E402

FIXTURES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")


def _fixture(name: str) -> str:
    path = os.path.join(FIXTURES, name)
    if not os.path.exists(path):
        from tests import make_fixtures

        make_fixtures.main()
    return path


def _images(prod: str, stage: str):
    expected = fitz.open(_fixture(prod))
    actual = fitz.open(_fixture(stage))
    try:
        return validate_images(expected, actual, None)
    finally:
        expected.close()
        actual.close()


def _content(prod: str, stage: str):
    prod_path, stage_path = _fixture(prod), _fixture(stage)
    expected = fitz.open(prod_path)
    actual = fitz.open(stage_path)
    try:
        result = validate_content(expected, actual, prod_path, stage_path, None)
        return result[0] if isinstance(result, tuple) else result
    finally:
        expected.close()
        actual.close()
        reset_table_cache()


def _tables(prod: str, stage: str):
    prod_path, stage_path = _fixture(prod), _fixture(stage)
    expected = fitz.open(prod_path)
    actual = fitz.open(stage_path)
    try:
        return validate_tables(expected, actual, prod_path, stage_path, None)
    finally:
        expected.close()
        actual.close()
        reset_table_cache()


# --- images ----------------------------------------------------------------


def test_figure_moved_to_next_page_in_same_section_is_not_a_finding():
    """The whole point of matching by appearance across the section: STAGE
    paginates differently, and a figure landing on the next page is fine so
    long as it is still under the same heading."""
    result = _images("images_prod.pdf", "images_stage_ok.pdf")
    assert result.message_counts == {}, result.message_counts
    row = result.summary_rows[0]
    assert row["matched"] == 3
    assert row["missing"] == 0 and row["differs"] == 0
    assert row["moved_page"] == 1, "the repaginated figure should be recorded as moved, not lost"


def test_replaced_figure_is_reported_as_a_content_difference():
    result = _images("images_prod.pdf", "images_stage_swapped.pdf")
    assert result.message_counts.get("Image content differs") == 1, result.message_counts
    assert result.message_counts.get("Image missing") is None
    assert result.summary_rows[0]["differs"] == 1


def test_removed_figure_is_reported_as_missing():
    result = _images("images_prod.pdf", "images_stage_missing.pdf")
    assert result.message_counts.get("Image missing") == 1, result.message_counts
    assert result.summary_rows[0]["missing"] == 1


def test_a_figure_that_came_through_soft_is_reported_as_blurred():
    """The same picture, rendered at a materially lower effective resolution in
    Staging - unreadable in print, and invisible to every other check: the
    fingerprint correlates at ~1.0 because it IS the same picture, the extent is
    identical, and it decodes fine so it is not "broken"."""
    from PIL import Image, ImageFilter

    from pdfval.imagefp import sharpness

    src_pdf = fitz.open(_fixture("images_prod.pdf"))
    try:
        pix = src_pdf[0].get_pixmap(dpi=150)
        picture = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
    finally:
        src_pdf.close()

    def page_of(image) -> fitz.Document:
        import io

        buf = io.BytesIO()
        image.save(buf, format="PNG")
        doc = fitz.open()
        page = doc.new_page(width=image.width * 0.5, height=image.height * 0.5)
        page.insert_image(page.rect, stream=buf.getvalue())
        return doc

    sharp = page_of(picture)
    soft = page_of(picture.filter(ImageFilter.GaussianBlur(3.0)))
    try:
        rect = sharp[0].rect
        box = (rect.x0, rect.y0, rect.x1, rect.y1)
        sharp_score = sharpness(sharp, 0, box)
        soft_score = sharpness(soft, 0, box)
        assert sharp_score and soft_score, (sharp_score, soft_score)
        # The metric has to separate them clearly, or the check cannot.
        assert soft_score / sharp_score < 0.65, (sharp_score, soft_score)
        # ...and must NOT call the sharp original blurred against itself.
        assert sharpness(sharp, 0, box) / sharp_score >= 0.65
    finally:
        sharp.close()
        soft.close()


def test_same_figure_rendered_wider_is_counted_but_not_flagged():
    """The picture is unchanged, only its width - that is a resize, not a swap
    and not a loss, so it is COUNTED in the figure summary and raises no issue.

    Reporting it per figure buried the findings that break a document (a
    dropped label, a stripped callout, a blank render) under rows nobody acts
    on, so `_check_dimensions` now only records it.
    """
    result = _images("images_prod.pdf", "images_stage_wider.pdf")
    counts = result.message_counts
    assert counts.get("Image missing") is None, counts
    assert counts.get("Image content differs") is None, counts
    assert counts.get("Image width changed") is None, counts
    assert counts.get("Image size changed") is None, counts
    # The resize is still visible where it belongs: the figure-by-figure table.
    assert result.summary_rows[0]["resized"] == 1
    assert result.summary_rows[0]["matched"] == 3  # still counted as the same picture


def test_identical_documents_report_no_figure_findings():
    result = _images("images_prod.pdf", "images_prod.pdf")
    assert result.message_counts == {}, result.message_counts
    assert result.summary_rows[0]["matched"] == result.summary_rows[0]["expected_figures"]


# --- content: text on the next page / re-segmented text --------------------


def test_text_that_reflowed_onto_the_next_page_is_not_reported_missing():
    """The reviewer's own check: a sentence that merely moved to the next page
    of the same section is present, not missing. Production keeps paragraph C
    on page 1; Staging pushes it to page 2."""
    result = _content("content_prod.pdf", "content_stage_reflowed.pdf")
    offending = [
        i for i in result.issues
        if i.message in ("Missing text", "Added text")
        and "Repeat this step until the screen is clean" in " ".join(
            (i.details.get("expected") or []) + (i.details.get("actual") or [])
        )
    ]
    assert not offending, [i.details for i in offending]


def test_sentence_glued_to_its_neighbour_by_a_dropped_space_is_not_reported_missing():
    """Production drops the space after a full stop ("completely.If"), so that
    document keeps two sentences as one. The second sentence still exists in
    both documents and must not read as missing/added."""
    result = _content("content_prod.pdf", "content_stage_glued.pdf")
    text_issues = [i for i in result.issues if i.message in ("Missing text", "Added text", "Changed text")]
    for issue in text_issues:
        blob = " ".join((issue.details.get("expected") or []) + (issue.details.get("actual") or []))
        assert "avoid spreading the grease around" not in blob, issue.details


def test_identical_documents_report_no_content_findings():
    result = _content("content_prod.pdf", "content_prod.pdf")
    assert not [i for i in result.issues if i.message in ("Missing text", "Added text", "Changed text")]


def test_text_diff_finding_carries_its_wording_not_a_screenshot():
    """A Missing/Added text finding shows the TEXT, not a picture of it.

    The crops these findings used to carry said nothing the wording didn't -
    and on the side with nothing corresponding, a "context" crop pointed at an
    unrelated place and read as a false claim. The exact Production/Staging
    wording is the evidence here; the side-by-side browser shows the same text
    in its real page context. (Visual content findings - a dropped bold run, an
    encoding regression - do still carry crops; see `_attach_screenshots`.)
    """
    import tempfile

    prod_path = _fixture("content_prod.pdf")
    stage_path = _fixture("content_stage_edited.pdf")  # one paragraph dropped, one added
    out = tempfile.mkdtemp()
    expected = fitz.open(prod_path)
    actual = fitz.open(stage_path)
    try:
        res = validate_content(expected, actual, prod_path, stage_path, out)
        result = res[0] if isinstance(res, tuple) else res
    finally:
        expected.close()
        actual.close()
        reset_table_cache()

    one_sided = [i for i in result.issues if i.message in ("Missing text", "Added text")]
    assert one_sided, "expected a Missing and an Added finding for the edited paragraph"
    for issue in one_sided:
        d = issue.details or {}
        assert not d.get("prod_screenshot"), d
        assert not d.get("stage_screenshot"), d
        # The finding still has to say WHAT changed, on the side that has it.
        side = "expected" if issue.message == "Missing text" else "actual"
        assert d.get(side), d


# --- tables ----------------------------------------------------------------


def test_repeated_header_on_every_continuation_page_passes():
    result = _tables("tables_prod.pdf", "tables_stage_ok.pdf")
    assert "Table header row not repeated on continuation page" not in result.message_counts
    row = result.summary_rows[0]
    assert row["header_repeated"] == "Yes"
    assert row["actual_span"] == "3 pages"


def test_missing_header_on_continuation_pages_is_an_error():
    """The rule the report exists to enforce: a Staging table that runs onto
    another page must reprint its header there."""
    result = _tables("tables_prod.pdf", "tables_stage_noheader.pdf")
    count = result.message_counts.get("Table header row not repeated on continuation page")
    assert count == 2, result.message_counts  # the table spans three pages

    issues = [i for i in result.issues if i.message.startswith("Table header row not repeated")]
    assert [i.page for i in issues] == [1, 2], "should name the continuation pages, not the first page"
    for issue in issues:
        assert issue.severity == "error"
        assert issue.details["header_row"].startswith("Item")
        # The row actually printed there is quoted, so the reader can see what
        # took the header's place.
        assert issue.details["first_row_on_continuation"].startswith("Setting")
    assert result.summary_rows[0]["header_repeated"] == "NO"
    assert result.summary_rows[0]["status"] == "Issues"


def test_missing_header_is_reported_even_without_a_production_counterpart():
    """The rule holds against Staging alone - it must not depend on the table
    pairing with anything in Production."""
    result = _tables("images_prod.pdf", "tables_stage_noheader.pdf")
    assert result.message_counts.get("Table header row not repeated on continuation page") == 2


def test_identical_documents_report_no_table_findings():
    result = _tables("tables_prod.pdf", "tables_prod.pdf")
    assert result.message_counts == {}, result.message_counts


def test_table_running_past_the_right_margin_is_captured():
    """A Staging table whose right edge sits well past the page's established
    content margin must be flagged."""
    result = _tables("tables_prod.pdf", "tables_stage_overflow.pdf")
    n = result.message_counts.get("Table breaking the margins")
    assert n and n >= 1, result.message_counts
    issue = next(i for i in result.issues if i.message == "Table breaking the margins")
    assert "right margin by" in issue.details["overflow"]
    # and it must NOT fire when the table sits inside the margin
    ok = _tables("tables_prod.pdf", "tables_stage_ok.pdf")
    assert "Table breaking the margins" not in ok.message_counts


def _run_all() -> int:
    failures = 0
    for name, fn in sorted(globals().items()):
        if not name.startswith("test_") or not callable(fn):
            continue
        try:
            fn()
            print(f"PASS {name}")
        except AssertionError as exc:
            failures += 1
            print(f"FAIL {name}: {exc}")
    print(f"\n{failures} failure(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(_run_all())
